### ISSUE TITLE
data文件夹缺失问题

### ISSUE THREAD

**Issue by HFourier** [qyy2003/FTPipeHD#2]
我在init.py文件发现这一行` parser.add_argument('--data', type=str, default='../data/voc.yaml', help='data.yaml path')` 但是实际上在github中我并没有找到相关文件夹，请问我该如何获得他们？

**Comment by qyy2003** [comment]
As stated in the ```README.md```, it's adapted from  *FTPipeHD*. VOC is implemented in the original code but is no longer maintained in this version. If you need the original code, please email the auther of  *FTPipeHD* for help.
